Added better parameter omission checking to script

diff --git a/mysql-csv b/mysql-csv
--- a/mysql-csv
+++ b/mysql-csv
@@ -8,11 +8,22 @@
 DATABASE="$1"
 TABLE="$2"
 FIELDS="$3"
-TMP=`mktemp -p /tmp -u mysql-csv.XXXXXX`
+
+if [ -z "$DATABASE" ]; then
+	echo "Usage: mysql-csv <database> <table> [fields]"
+	exit 1
+fi
+
+if [ -z "$TABLE" ]; then
+	echo "Table name missing"
+	exit 1
+fi
 	
 if [ -z "$FIELDS" ]; then
 	FIELDS="*"
 fi
+
+TMP=`mktemp -p /tmp -u mysql-csv.XXXXXX`
 
 mysql "$DATABASE" -e "SELECT $FIELDS INTO OUTFILE '$TMP' FIELDS TERMINATED BY ',' ENCLOSED BY '\"' ESCAPED BY '\\\\' LINES TERMINATED BY '\n' FROM $TABLE"
 
